# Generated by Django 2.1 on 2018-11-16 00:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('uvfriendly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomecanal', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150)),
                ('campo_01', models.CharField(blank=True, max_length=50, null=True)),
                ('campo_02', models.CharField(blank=True, max_length=50, null=True)),
                ('campo_03', models.CharField(blank=True, max_length=50, null=True)),
                ('campo_04', models.CharField(blank=True, max_length=50, null=True)),
                ('campo_05', models.CharField(blank=True, max_length=50, null=True)),
                ('campo_06', models.CharField(blank=True, max_length=50, null=True)),
                ('campo_07', models.CharField(blank=True, max_length=50, null=True)),
                ('campo_08', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('latitude', models.IntegerField(blank=True, default=0, null=True)),
                ('longitude', models.IntegerField(blank=True, default=0, null=True)),
                ('elevation', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uvfriendly.Usuarios')),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
