# Generated by Django 2.1 on 2018-12-05 01:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('uvfriendly', '0003_document'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='document',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
